name: nasa
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi=0.110.0
  - uvicorn=0.29.0
  - numpy=1.26
  - pillow=10
  - pvl
  - glymur=0.12
  - rasterio=1.3
  - gdal=3.6
  - astropy=6.1
  - matplotlib=3.9
  - pandas=2.2
  - seaborn=0.13
